name: "📋 Task"
description: "Criar uma nova tarefa"
title: "[Task] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Nova Tarefa
        Preencha os campos abaixo para criar uma nova tarefa.

  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Descreva detalhadamente o que precisa ser feito
      placeholder: |
        Descreva o objetivo da tarefa, contexto necessário e qualquer informação relevante para sua execução.
    validations:
      required: true

  - type: textarea
    id: requisitos
    attributes:
      label: Requisitos
      description: Liste os requisitos funcionais e técnicos
      placeholder: |
        1. Requisito 1
        2. Requisito 2
        3. Requisito 3
    validations:
      required: true

  - type: textarea
    id: criterios
    attributes:
      label: Critérios de Aceitação
      description: Defina os critérios que determinam quando a tarefa está completa
      placeholder: |
        - [ ] Critério 1
        - [ ] Critério 2
        - [ ] Critério 3
    validations:
      required: false

  - type: dropdown
    id: tipo
    attributes:
      label: Tipo
      description: Qual o tipo desta tarefa?
      options:
        - Feature
        - Bug
        - Improvement
        - Refactor
        - Documentation
        - Chore
    validations:
      required: true

  - type: textarea
    id: contexto-adicional
    attributes:
      label: Contexto Adicional
      description: Screenshots, links, referências ou qualquer informação extra
      placeholder: Adicione aqui qualquer contexto adicional relevante
    validations:
      required: false
